---
title: El modo en espera pasiva lanza "DataStoreException Record no existe"
description: Descripción
solution: Experience Manager
product: Experience Manager
applies-to: Experience Manager
keywords: KCS,AEM,coldstandby,DataStoreException
resolution: Resolution
internal-notes: https://issues.apache.org/jira/browse/OAK-8202,https://jira.corp.adobe.com/browse/GRANITE-11668
bug: false
article-created-by: Vincent Frey
article-created-date: 5/12/2022 3:39:59 PM
article-published-by: Vincent Frey
article-published-date: 5/12/2022 3:40:16 PM
version-number: 2
article-number: KA-15610
dynamics-url: https://adobe-ent.crm.dynamics.com/main.aspx?forceUCI=1&pagetype=entityrecord&etn=knowledgearticle&id=8e6000c7-09d2-ec11-a7b5-0022480a8683
exl-id: d37d0338-be4f-4660-a4b2-cd1179717e07
source-git-commit: e8f4ca2dd578944d4fe399074fab461de88ad247
workflow-type: tm+mt
source-wordcount: '311'
ht-degree: 0%

---

# El modo en espera pasiva lanza &quot;DataStoreException Record no existe&quot;

## Descripción


<b>Problema:</b>
El modo de espera en frío con el archivo dedicado Datastore genera una advertencia en el blobid que falta, como el que aparece en 1.

<b>Detalles:</b>
Esto es solo una advertencia, no un error. Se debe a que el almacén de datos no tiene forma de verificar si existe un binario localmente, excepto al intentar cargar blob id.
Si se carga el id, los registros no muestran esta advertencia. Sin embargo, si no se encuentra, el modo de espera sabe que debe sincronizarlo, por lo que vemos la advertencia 1 en los registros.


1: *\*WARN\* standby-run-1 org.apache.jackrabbit.oak.plugins.blob.datastore.DataStoreBlobStore Error al cargar bytes desde el vapor al recuperar el id f68a92b34779bbd194184251ec 916370f3ebd301d6e32a8980aad070d57a1845#25522
<br>java.util.concurrent.ExecutionException: java.io.IOException: org.apache.jackrabbit.core.data.DataStoreException: Registro f68a92b34779bbd194184251ec916370f3ebd301d6e32a8980aad070d57a18 45 no existe
<br>    en org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1017) org.apache.jackrabbit.oak-core-spi:1.10.3
<br>...
<br>Causado por: org.apache.jackrabbit.core.data.DataStoreException: El registro cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c20 no existe
<br>    en org.apache.jackrabbit.core.data.AbstractDataStore.getRecord(AbstractDataStore.java:59)*


## Resolución


Funciona como está diseñado y no indica ningún problema con File DataStore.

<b>Para confirmar:</b>

- Ejemplo de id. de blob que se muestra como ausente en los registros: &quot;cabdc49c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c49c29c22 0&quot;
- Para esta id de blob, la dirección del sistema de archivos debe ser: &quot;ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1935a2c444443333333333030000000000000000000000000000000000000000000000000000000000 9c20&quot;
- Busque en el sistema de archivos en la instancia independiente y compruebe si el archivo con nombre está presente en el almacén de datos.
- Dentro de /repository/datastore, utilice el comando list (ls -ald): &quot;ls -ald ca/bd/c4/9c6562afe71da796b57c2d1a6a3495026dfafff4d1073f1933933 5a2c49c20&quot;
- Debería poder ver el archivo y confirmar que no falta el id de blob
